kind: PersistentVolume
apiVersion: v1
metadata:
  name: flaskapi-pv-volume
  namespace: branka
  labels:
    type: local
    app: flaskapi
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/branka/saska/models"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flaskapi-pv-claim
  namespace: branka
  labels:
    app: flaskapi
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi