---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: branka
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: "IfNotPresent"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flaskapi-secrets-td6b9b2c9c
              key: password
        ports:
        - containerPort: 3306
          name: db-container
        volumeMounts:
          - name: mysql-pv-volume-flask
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv-volume-flask
          persistentVolumeClaim:
            claimName: mysql-pv-claim-flask


---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: branka
  labels:
    app: db
spec:
  ports:
  - port: 3306
    nodePort: 30004
    targetPort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: db
  type: NodePort